services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql

  frontend:
    build: ./frontend  #Dockerfile /frontend
    container_name: vue
    restart: always
    ports:
      - "4000:3000" # Map to port 4000
    environment:
      - NUXT_HOST=0.0.0.0 # acess from outside
    depends_on:
      - load-balancer

  minitwitter-1:
    build: .      
    image: minitwitter-app
    container_name: minitwitter-1

    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
    depends_on:
        redis:        # needed to start Redis before API
          condition: service_healthy
        db:            # needed to start DB befor API
          condition: service_started
    restart: always

  minitwitter-2:
    image: minitwitter-app # we can reuse the same image for the second instance
    container_name: minitwitter-2

    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
    depends_on:
        redis:        # needed to start Redis before API
          condition: service_healthy
        db:            # needed to start DB befor API
          condition: service_started
    restart: always

  sentiment-worker:
    image: minitwitter-app # reuse the same image for the worker
    container_name: sentiment-worker

    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
      REDIS_HOST: redis
      OLLAMA_HOST: http://ollamaforminitwitter:11434
      SERVER_ROLE: worker
    depends_on:
      redis:        # needed to start Redis before API
        condition: service_healthy
      db:            # needed to start DB befor API
        condition: service_started
    restart: always

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    restart: always
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minitwitter-1
      - minitwitter-2
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollamaforminitwitter
    restart: always
    ports:
      - "11434:11434" # Ollama API port, it doesn't conflict with installed version
    volumes:
      - ./docker-data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" # Redis default port
      - "8001:8001" # Redis Web UI port
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3100:3000"

volumes:  
  postgres_data: