services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data:/var/lib/postgresql/data

  minitwitter-1:
    build: .          # to build docker image with the Dockerfile in this directory
    container_name: minitwitter-1

    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
    depends_on:
        redis:        # needed to start Redis before API
          condition: service_healthy
        db:            # needed to start DB befor API
          condition: service_started
    restart: always

  minitwitter-2:
    build: .          # to build docker image with the Dockerfile in this directory
    container_name: minitwitter-2

    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
    depends_on:
        redis:        # needed to start Redis before API
          condition: service_healthy
        db:            # needed to start DB befor API
          condition: service_started
    restart: always

  sentiment-worker:
    build: .      
    container_name: sentiment-worker
    environment:
      DATABASE_URL: postgresql://postgres:supersecret123@db:5432/minitwitter
      REDIS_HOST: redis
      OLLAMA_HOST: http://ollamaforminitwitter:11434
      SERVER_ROLE: worker
    depends_on:
      redis:        # needed to start Redis before API
        condition: service_healthy
      db:            # needed to start DB befor API
        condition: service_started
    restart: always

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    restart: always
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minitwitter-1
      - minitwitter-2
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollamaforminitwitter
    restart: always
    ports:
      - "11434:11434" # Ollama API port, it doesn't conflict with installed version
    volumes:
      - ./docker-data/ollama:/root/.ollama

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" # Redis default port
      - "8001:8001" # Redis Web UI port
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
